### CREAR USUARIO
POST http://localhost:8000/api/auth/register HTTP/1.1
content-type: application/json

{
    "nombre": "Francisco",
    "apellido": "Boisier",
    "correo": "sephitor2@gmail.com",
    "password" : "123456"
}

### LOGIN DEL USUARIO
POST http://localhost:8000/api/auth/login HTTP/1.1
content-type: application/json

{
    "correo": "sephitor1@gmail.com",
    "password" : "123456"
}

### LISTAR TODOS LOS USUARIOS
GET http://localhost:8000/api/usuarios HTTP/1.1
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2MWExNjhlOGI5ZDRkM2Q1ZmUyMGRhMDMiLCJlbWFpbCI6InNlcGhpdG9yMUBnbWFpbC5jb20iLCJmaXJzdG5hbWUiOiJGcmFuY2lzY28iLCJsYXN0bmFtZSI6IkJvaXNpZXIiLCJpYXQiOjE2Mzg1NDIzOTYsImV4cCI6MTYzODU0OTU5Nn0.4nSZpiAf04W1qZb0BByaJM_6nqxiioedzgSSLL74HoI

### LISTAR TODOS LOS USUARIOS
GET http://localhost:8000/api/usuarios/propio HTTP/1.1
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2MWExNjhlOGI5ZDRkM2Q1ZmUyMGRhMDMiLCJlbWFpbCI6InNlcGhpdG9yMUBnbWFpbC5jb20iLCJmaXJzdG5hbWUiOiJGcmFuY2lzY28iLCJsYXN0bmFtZSI6IkJvaXNpZXIiLCJpYXQiOjE2Mzg1NDIzOTYsImV4cCI6MTYzODU0OTU5Nn0.4nSZpiAf04W1qZb0BByaJM_6nqxiioedzgSSLL74HoI